name: Deployment
on: [push]

jobs:
  build:
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Webpack Build Production
        run: yarn prod
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.0.1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_API }}
          NETLIFY_SITE_ID: '14848df1-1333-44c4-8eca-e8f7203721e2'
          build_directory: 'dist'
          NETLIFY_DEPLOY_TO_PROD: true
